on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install dependencies
      run: |
        npm ci
        npm install -g pkg
    - name: Build
      run: |
        pkg main.js -t node18-win-x64 -o MyuuGrinder.exe
        mkdir notifier
        Copy-Item -Path .\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -Destination .\notifier\ -Force
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MyuuGrinder
        path: |
          .\MyuuGrinder.exe
          .\notifier/snoretoast-x64.exe
    
