on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Auto Build
      uses: lando/pkg-action@v4.0.0
      with:
        entrypoint: main.js
        arch: x64
        node-version: 18 # optional, default is 16
